Front: login and register
CastledChess/Front pull request #40
Opened 2024-10-24 08:14 UTC by wijdanepitech

2024-10-25 08:25 UTC, Fautour commented on src/pages/Register.tsx
> +import React from 'react';
You need to remove this line and after that we can merge

2024-10-25 08:25 UTC, Fautour commented on src/pages/Login.tsx
> +import React from 'react';
You need to remove this line and after that we can merge

2024-10-25 08:33 UTC, Fautour requested changes

2024-10-25 08:33 UTC, Fautour commented on src/pages/Register.tsx
> +import React from 'react';
```suggestion
```

2024-10-25 08:33 UTC, Fautour commented on src/pages/Login.tsx
> +import React from 'react';
```suggestion
```

2024-11-01 15:34 UTC, Lxdovic commented
branch moves to feat/auth see #56

2024-11-01 15:34 UTC, closed without merging